events{}

http{
    upstream currency-converter {
        server currency-converter:8079;    
    }
    upstream currency-converte-history {
        server currency-converter-history:8080;
    }
    
    server {
        listen 80;

        location /api/converter/ {
            rewrite ^/api/converter/(.*)$ /$1 break;
            proxy_pass http://currency-converter;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/history/ {
            rewrite ^/api/history/(.*)$ /$1 break;
            proxy_pass http://currency-converter-history;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 'Currency API Gateway is running via Docker Swarm';
            add_header Content-Type text/plain;
        }
    }
}
