# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0
        
    - name: Restore dependencies
      run: dotnet restore backend/CurrencyConverter.sln
    
    - name: Build
      run: dotnet build backend/CurrencyConverter.sln --no-restore
    
    - name: Test
      run: dotnet test backend/CurrencyConverter.sln --no-build --verbosity normal

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: test-backend
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    permissions:
      id-token: write
      contents: read 
      pages: write 
      deployments: write 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './frontend'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

